####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                          CSVaddon                                            | #
# |                                       by  Architetto                                         | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

Auto-sell toggle: true
Auto-sell day : Sunday
Random Auto-sell time: false
Auto-sell time : 10 #Se Random Auto-sell time è "false" allora ... Corrisponde all'ora (di default alle 10 di mattina)
